// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN6J0pK4wUxHpXRXeuYpsOkuXhqBbyM_s',
    appId: '1:25567954763:web:b9d46af9a6c953e5020ace',
    messagingSenderId: '25567954763',
    projectId: 'registronotas2025-a11e5',
    authDomain: 'registronotas2025-a11e5.firebaseapp.com',
    storageBucket: 'registronotas2025-a11e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX8wUlB3TJwR-E-EFKBdDOC51lrKgxLvA',
    appId: '1:25567954763:android:2a9cd1bfbf767f33020ace',
    messagingSenderId: '25567954763',
    projectId: 'registronotas2025-a11e5',
    storageBucket: 'registronotas2025-a11e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcR3JKCgXDhcUQHwMKu9c14d00daE1gr4',
    appId: '1:25567954763:ios:957b6b6d984f5fd3020ace',
    messagingSenderId: '25567954763',
    projectId: 'registronotas2025-a11e5',
    storageBucket: 'registronotas2025-a11e5.firebasestorage.app',
    iosBundleId: 'com.example.registroClases',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcR3JKCgXDhcUQHwMKu9c14d00daE1gr4',
    appId: '1:25567954763:ios:957b6b6d984f5fd3020ace',
    messagingSenderId: '25567954763',
    projectId: 'registronotas2025-a11e5',
    storageBucket: 'registronotas2025-a11e5.firebasestorage.app',
    iosBundleId: 'com.example.registroClases',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN6J0pK4wUxHpXRXeuYpsOkuXhqBbyM_s',
    appId: '1:25567954763:web:34d731263fef6738020ace',
    messagingSenderId: '25567954763',
    projectId: 'registronotas2025-a11e5',
    authDomain: 'registronotas2025-a11e5.firebaseapp.com',
    storageBucket: 'registronotas2025-a11e5.firebasestorage.app',
  );
}
